spring:
  profiles:
    active: aws
  application:
    name: product-services
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  #    hikari:
  #      connection-timeout: 2000 #ms
  #      maximum-pool-size: 50
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      connect-timeout: 2s
      host: ${REDIS_HOST}
      port: 6379
      timeout: 1s
      password: ${REDIS_PASSWORD}

cloud:
  aws:
    s3:
      region: ap-northeast-2
      bucket: yoger-product-test
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
#  gcp:
#    gcs:
#      project-id: rich-sunlight-434701-c1
#      bucket: gcs-yoger
#      credentials-path: yoger-gcs.json

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 8080  # 애플리케이션 포트 (필요에 따라 변경)